Eval reset for all names in python interpreter
trikset/trikRuntime pull request #604
Opened 2020-10-25 18:25 UTC by khodand

It could be done in system.py in theory (we can create something like `__trik_all_aliases_list__`  and clear all names except these)

2020-10-25 19:09 UTC, iakov requested changes

2020-10-25 19:09 UTC, iakov commented on trikScriptRunner/src/pythonEngineWorker.cpp
> +	mMainContext.evalScript("[delattr(sys.modules[__name__], x) for x in dir() if x[0] != '_' and x != 'sys']");
Предлагаю перенести в system.py.
Но собственные объекты, которые из C++ передаём, надо переименовать в _trik_brick_cpp и _trik_script_cpp, а в system.py сделать в начале где-то `brik = _trik_brick_cpp`  
Так же, наверное, будет уместно сделать `gc.collect()` сразу после чистки.
Ещё не понятно, почему sys не чистится?

2020-10-25 19:17 UTC, khodand commented on trikScriptRunner/src/pythonEngineWorker.cpp
> +	mMainContext.evalScript("[delattr(sys.modules[__name__], x) for x in dir() if x[0] != '_' and x != 'sys']");
Переносить в system.py - легко, но масштабируемость станет хуже:
Нужно будет завести словарь со всеми используемыми именами из `trikControl::` чтобы их не чистить, а потом еще его поддерживать. 
`sys` не чистится, потому что мы `sys.modules` использовать хотим.

2020-10-25 19:21 UTC, khodand commented on trikScriptRunner/src/pythonEngineWorker.cpp
> +	mMainContext.evalScript("[delattr(sys.modules[__name__], x) for x in dir() if x[0] != '_' and x != 'sys']");
`'trikControl::BatteryInterface', 'trikControl::BrickInterface', 'trikControl::ColorSensorInterface', 'trikControl::DisplayInterface', 'trikControl::DisplayWidgetInterface', 'trikControl::EncoderInterface', 'trikControl::EventCodeInterface', 'trikControl::EventDeviceInterface', 'trikControl::EventInterface', 'trikControl::FifoInterface', 'trikControl::GamepadInterface', 'trikControl::GyroSensorInterface', 'trikControl::I2cDeviceInterface', 'trikControl::KeysInterface', 'trikControl::LedInterface', 'trikControl::LineSensorInterface', 'trikControl::MarkerInterface', 'trikControl::MotorInterface', 'trikControl::ObjectSensorInterface', 'trikControl::PwmCaptureInterface', 'trikControl::SensorInterface', 'trikControl::SoundSensorInterface', 'trikControl::VectorSensorInterface'`

2020-10-26 07:21 UTC, iakov requested changes

2020-10-26 07:21 UTC, iakov commented on trikScriptRunner/src/pythonEngineWorker.cpp
> +				"import gc;"
```suggestion
				"from gc import collect;"
```

2020-10-28 07:37 UTC, iakov submitted a review, later dismissed

2020-10-29 12:06 UTC, iakov commented
Надо ребейзнуть на мастер.

2020-10-29 19:48 UTC, iakov approved these changes

2020-10-29 19:48 UTC, merged