Returns median data from read
trikset/trikRuntime pull request #626
Opened 2020-12-03 13:20 UTC by khodand

Fixes #620

2020-12-03 14:32 UTC, iakov approved these changes

2020-12-03 14:32 UTC, iakov commented on trikControl/src/analogSensor.h
> +	QVector<int> mPreviousData;
Нет нужды заводить вектор для 2 значений. Можно просто mReading1, mReading2 или ещё как-то, избегая лишних накладных расходов на вектор.

2020-12-04 08:55 UTC, iakov approved these changes

2020-12-04 08:55 UTC, iakov commented on trikControl/src/analogSensor.cpp
> +	if (mReadData1 + mReadData2 < 0) {
Точно ли оно работает? Если 'mReadData1 == -1' , а `с` приходит как 0? Зачем вообще эта проверка? Ну пусть инициализированы переменные нулём, и пусть всегда используются эти значения. Это же только после первого запуска прошивки первое чтение выдаст не ту медиану. Можно, конечно, аккуратно обработать эту ситуацию.

2020-12-04 08:55 UTC, iakov commented on trikControl/src/analogSensor.cpp
> +
лучше вот сюда.
Надо принять новое значение, сохранить его, а уж потом разбираться. При этом не факт, что меньше нуля -- это плохо. Но сейчас да, меньше нуля не бывает хороших значений в этой функции.

2020-12-04 08:55 UTC, iakov commented on trikControl/src/analogSensor.h
> +	int mReadData1 = -1;
Инициализировать лучше через `{ -1 }`

2020-12-04 08:57 UTC, iakov requested changes
С вектором раньше хотя бы корректным выглядило, я ставил "аппрув", но этот вариант стал хуже. 
Надо доделать.

2020-12-05 09:47 UTC, iakov requested changes

2020-12-05 09:47 UTC, iakov commented on trikControl/src/analogSensor.cpp
> +	return b;
```suggestion
	return b < 0 ? c : b;
```

2020-12-05 09:47 UTC, iakov commented on trikControl/src/analogSensor.cpp
> +	return b;
Идея: возможно так мы защитимся от случайной -1, когда у нас только первое значение пришло, когда `a == -1 && b == -1`

2020-12-05 09:47 UTC, iakov commented on trikControl/src/rangeSensorWorker.cpp
> +	return b;
```suggestion
	return b < 0 ? c : b;
```

2020-12-05 10:12 UTC, khodand commented on trikControl/src/analogSensor.cpp
> +	return b;
А у нас в аналоговых датчиках тоже не бывает отрицательных значений?

2020-12-06 09:57 UTC, iakov commented
Поскольку для аналоговых сенсоров так нельзя делать, пока закрываю этот ПР

2020-12-06 09:57 UTC, closed without merging