TrikAbstractTimer class in scriptControl
trikset/trikRuntime pull request #635
Opened 2021-01-18 14:15 UTC by khodand

2021-01-18 14:36 UTC, iakov requested changes

2021-01-18 14:36 UTC, iakov commented on trikScriptRunner/include/trikScriptRunner/trikAbstractTimer.h
> +	virtual bool isTicking() const = 0;
А зачем нам всё этом сейчас? Надо сразу убрать isTicking и прочее, если всё равно мы будем делать прокси на стандартный таймер.

2021-01-18 14:36 UTC, iakov commented on trikScriptRunner/include/trikScriptRunner/trikAbstractTimer.h
> +	Q_INVOKABLE virtual void stop() = 0;
Слоты и так Q_INVOKABLE.

2021-01-18 14:36 UTC, iakov commented on trikScriptRunner/include/trikScriptRunner/trikAbstractTimer.h
> +protected slots:
Почему он `protected`? На то есть весомые аргументы?

2021-01-18 14:36 UTC, iakov commented on trikScriptRunner/src/scriptExecutionControl.cpp
> +	qRegisterMetaType<TrikAbstractTimer *>("TrikAbstractTimer*");
Наверное, не здесь, а так же, как для всех других типов, связанных с brick. Мы же здесь интерфейсы устройств не регистрируем.

2021-01-18 14:36 UTC, iakov commented on trikScriptRunner/src/scriptExecutionControl.cpp
> +	TrikRealTimer *result = new TrikRealTimer();
`auto`!

2021-01-18 14:36 UTC, iakov commented on trikScriptRunner/src/trikAbstractTimer.cpp
> +	emit timeout();
Не уверен, что нужен этот метод, да ещё у класса с именем `Abstract`

2021-01-18 14:36 UTC, iakov commented on trikScriptRunner/trikScriptRunner.pro
> +	$$PWD/include/trikScriptRunner/trikRealTimer.h \
точно ли надо в PUBLIC_HEADERS добавлять заголовочный файл конкретной реализации? Нам надо переиспользовать реализацию где-то?

2021-01-18 14:38 UTC, khodand commented on trikScriptRunner/trikScriptRunner.pro
> +	$$PWD/include/trikScriptRunner/trikRealTimer.h \
По идее можно переиспользовать в студии вместо такого же RealTimer

2021-01-18 16:31 UTC, khodand commented on trikScriptRunner/src/scriptExecutionControl.cpp
> +	qRegisterMetaType<TrikAbstractTimer *>("TrikAbstractTimer*");
Вынес в регистрацию в интерфейс. Это же не тип связанный с brick, этот как раз только со scriptExecutionControl

2021-01-20 18:43 UTC, iakov approved these changes

2021-01-20 18:45 UTC, merged