Do not delete active connections on connectionInfo
trikset/trikRuntime pull request #643
Opened 2021-02-28 23:23 UTC by khodand

2021-03-03 13:50 UTC, iakov requested changes

2021-03-03 13:50 UTC, iakov commented on trikNetwork/src/mailboxConnection.cpp
> +        if (parsedString.size() != 3) {
Форматирование отъехало?

2021-03-03 13:50 UTC, iakov commented on trikNetwork/src/mailboxServer.cpp
> +            const auto connectionObject = connection(ip, endpoint.connectedPort);
Форматирование?

2021-03-07 17:26 UTC, khodand commented on trikNetwork/src/mailboxServer.cpp
> +			if (connectedPort == 1) {
```suggestion
			if (connectedPort == -1) {
```

2021-03-08 05:31 UTC, iakov approved these changes

2021-03-08 05:32 UTC, merged